(()=>{function e(){let u=document.getElementById("blog-articles");if(u)if("undefined"==typeof ARTICLES_DATA)console.error("ARTICLES_DATA is not loaded. Make sure articles-data.js is loaded before blog-search.js"),u.innerHTML='<div class="blog-loading">Error: Article data failed to load. Please refresh the page.</div>';else{let a=document.getElementById("blog-search-input"),t=document.querySelector('.search-clear-button[data-target="blog-search-input"]'),n=document.getElementById("blog-categories"),r=document.getElementById("search-results-count"),l=document.getElementById("blog-no-results"),d=l?l.dataset.emptyMessage||"No articles found matching your search.":"",s=l?l.dataset.resetLabel||"Clear Search":"",c={rendered:!1},o="all",i="";var e;function g(e){if(u)if(u.innerHTML="",0===e.length)l&&(c.rendered||((t=document.createElement("p")).className="blog-no-results__message",t.textContent=d,l.appendChild(t),(t=document.createElement("button")).type="button",t.className="btn btn-secondary",t.textContent=s,t.addEventListener("click",()=>{a&&(a.value="",a.dispatchEvent(new Event("input",{bubbles:!0})),a.focus())}),l.appendChild(t),c.rendered=!0),l.hidden=!1,l.setAttribute("aria-hidden","false")),r&&(r.textContent="No articles found");else{var t;l&&(c.rendered&&(l.textContent="",c.rendered=!1),l.hidden=!0,l.setAttribute("aria-hidden","true"));let n=document.createDocumentFragment();e.forEach(e=>{var t=document.createElement("article"),a=(t.className="blog-article-card",`/insights/${e.slug}/`);t.innerHTML=`
                    <div class="blog-article-card__category">${e.category}</div>
                    <h2 class="blog-article-card__title">
                        <a href="${a}">${e.title}</a>
                    </h2>
                    <p class="blog-article-card__excerpt">${e.excerpt}</p>
                    <div class="blog-article-card__meta">
                        <time datetime="${e.lastUpdated}">${(e=>(e=new Date(e)).toLocaleDateString("en-GB",{year:"numeric",month:"long",day:"numeric"}))(e.lastUpdated)}</time>
                        <span class="blog-article-card__reading-time">${e.readingTime} min read</span>
                    </div>
                `,n.appendChild(t)}),u.appendChild(n),r&&(i?r.textContent=`Found ${e.length} article`+(1!==e.length?"s":""):r.textContent=`Showing ${e.length} article`+(1!==e.length?"s":""))}}function m(t){o=t,n&&n.querySelectorAll(".blog-category-btn").forEach(e=>{e.dataset.category===t?e.classList.add("active"):e.classList.remove("active")}),h()}function h(){let t=u&&u.dataset&&"true"===u.dataset.ssr;u&&!t&&u.classList.add("is-loading"),requestAnimationFrame(()=>{let e=ARTICLES_DATA;"all"!==o&&(e=e.filter(e=>e.category===o)),g(e=i?e.filter(e=>e.title.toLowerCase().includes(i)||e.excerpt.toLowerCase().includes(i)||e.category.toLowerCase().includes(i)):e),u&&(u.classList.remove("is-loading"),t)&&(u.dataset.ssr="hydrated")})}function b(){var e;a&&t&&(e=t.closest(".search-input-wrapper"))&&(e.dataset.hasValue=""!==a.value.trim()?"true":"false")}a&&(a.addEventListener("input",e=>{e=e.target.value,i=e.trim().toLowerCase(),h(),b()}),a.addEventListener("change",b)),t&&a&&(t.addEventListener("click",()=>{a.value="",b(),a.dispatchEvent(new Event("input",{bubbles:!0})),a.focus()}),b()),n&&(n.innerHTML="",(e=document.createElement("button")).className="blog-category-btn",e.type="button",e.dataset.category="all",e.textContent="All Articles",e.addEventListener("click",()=>m("all")),n.appendChild(e),getBlogCategories().forEach(e=>{var t=document.createElement("button");t.className="blog-category-btn",t.type="button",t.textContent=e,t.dataset.category=e,t.addEventListener("click",()=>m(e)),n.appendChild(t)})),m(o)}}"loading"===document.readyState?document.addEventListener("DOMContentLoaded",e):e()})();